# Generated by Django 2.0.6 on 2019-02-13 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_expense_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_expense_made',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_expense_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='reason',
            field=models.TextField(default='reason'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='value',
            field=models.CharField(default='value', max_length=255),
            preserve_default=False,
        ),
    ]
