# Generated by Django 2.0.6 on 2019-02-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20190213_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.CharField(help_text='Value of Expense', max_length=255),
        ),
    ]
