# Generated by Django 2.0.6 on 2019-02-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20190213_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_expense_made',
            new_name='date_expense_was_made',
        ),
    ]
