# Generated by Django 2.0.6 on 2019-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20190213_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='reason',
            field=models.TextField(help_text='Reasons Expense Was Made'),
        ),
    ]
