# Generated by Django 2.0.6 on 2019-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20190213_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_expense_was_made',
            field=models.DateField(blank=True, help_text='Date Expense Was Made', null=True),
        ),
    ]
