# Generated by Django 2.0.6 on 2019-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20190213_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_expense_was_made',
            field=models.DateField(blank=True, help_text='Enter Date Expense Was Made in this format YYYY-MM-DD', null=True),
        ),
    ]
