# Generated by Django 2.0.6 on 2019-02-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_auto_20190214_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='reason',
            field=models.CharField(help_text='Reasons Expense Was Made', max_length=255),
        ),
    ]
